services:
  messengerdb:
    image: postgres
    
  messenger.api:
    image: ${DOCKER_REGISTRY-}messengerapi
    build: 
      context: .
      dockerfile: services/messenger/Messenger.API/Dockerfile
  
  ocelot.gateway:
    image: ${DOCKER_REGISTRY-}ocetlotgateway
    build:
      context: .
      dockerfile: Gateways/Ocelot.Gateway/Dockerfile

  portainer:
    image: portainer/portainer-ce

volumes:
  pgdata:
  portainer_data: